### ISSUE TITLE
The hooks is not working with whmcs 8+ version

### ISSUE THREAD

**Issue by seyzed** [wolkenbauer/whmcs-cancelinvoice-hook#3]
Hello,

Is this hook still working? 
Apparently on WHMCS version 8.1.0 is not working. 

This is the code I am using:
`<?php

//https://github.com/wolkenbauer/whmcs-cancelinvoice-hook

if (!defined("WHMCS"))
    die("This file cannot be accessed directly");

use WHMCS\Database\Capsule;

add_hook('DailyCronJob',1,function($vars) 
{
//
// Change $overduedays to whatever you need. Default is cancel all invoices after being overdue for 90 days.
//
$overduedays=14;    
$invoices=Capsule::table("tblinvoices")->where("status","Unpaid")->where("duedate","<",date("Y-m-d",strtotime("-$overduedays days")))->get();

foreach($invoices as $invoice)
{
  //use UpdateInvoice API Call for changing the status, otherwise the InvoiceCancelled hook will not trigger 
  //and may affect other modules/apps which rely on this hook.
  $results = localAPI("UpdateInvoice",array("invoiceid"=>$invoice->id,"status"=>"Cancelled"));
  if ($results["result"]=="success") 
   logactivity("[INVOICECANCELHOOK] has cancelled Invoice ID: $invoice->id automatically.");
}
 
}); //hook`

My cronjob ran today but it didn't fire the cancelation of unpaid invoices that are overdue for more than 14 days. 

Any insight is appreciated.

Thank you

**Comment by wolkenbauer** [comment]
Hi,  
is the hook firing at all?
if not: where did you store the hook file and with which file permissions?
Is there anything in the whmcs or PHP logs?

**Comment by seyzed** [comment]
I checked this morning, apparently its working fine. I just had too few overdue invoices that I didn't notice. Checked the log, its firing correctly. Thank you
